// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtNdwYUDGuR9DZIfNV-QqTu9tJR4Of8bQ',
    appId: '1:545256551921:web:e25dc0bdb2498099a8c050',
    messagingSenderId: '545256551921',
    projectId: 'uas2023-12068',
    authDomain: 'uas2023-12068.firebaseapp.com',
    databaseURL: 'https://uas2023-12068-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas2023-12068.appspot.com',
    measurementId: 'G-GSX66M16TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApgIcWa3cIT0IeEIfbN8auwprBX5dPmZE',
    appId: '1:545256551921:android:bb50e3a5e4edeedda8c050',
    messagingSenderId: '545256551921',
    projectId: 'uas2023-12068',
    databaseURL: 'https://uas2023-12068-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas2023-12068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNIpI-Da7dn1cQ2ESgk_N_l3M1WA54xXA',
    appId: '1:545256551921:ios:c2f5530db981d535a8c050',
    messagingSenderId: '545256551921',
    projectId: 'uas2023-12068',
    databaseURL: 'https://uas2023-12068-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas2023-12068.appspot.com',
    iosClientId: '545256551921-ubl6r3vmdu166ih5bm8uivn78cb0qv02.apps.googleusercontent.com',
    iosBundleId: 'com.example.no2UasMade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNIpI-Da7dn1cQ2ESgk_N_l3M1WA54xXA',
    appId: '1:545256551921:ios:e59e1c40c33ce618a8c050',
    messagingSenderId: '545256551921',
    projectId: 'uas2023-12068',
    databaseURL: 'https://uas2023-12068-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas2023-12068.appspot.com',
    iosClientId: '545256551921-iq2657arhg7ht7kv6ep0m7snjp4ot19m.apps.googleusercontent.com',
    iosBundleId: 'com.example.no2UasMade.RunnerTests',
  );
}
